openapi: 3.0.1
info:
  title: Hotelios API
  description: This is Buyer API. Provides methods to get hotel info, find booking variants, book hotel rooms, get booking details, cancel existing booking.<br><br>
    **Change Log:**<br><br>
    **17.06.2025** - Added possibility to filter by hotel_types for Booking-Flow/Search method.<br><br>
    **01.05.2025** - Added information list into the price_breakdown field. Can be used to get info if city_tax included.<br><br>
    **01.05.2025** - Added possibility to filter by cancellation_type and meal_plans for Booking-Flow/Search method.<br><br>
    **06.03.2025** - Added hotel_confirmation_number field for Booking-Flow/Read method.<br><br>
    **20.11.2024** - Introduced Booking-Flow methods.
  version: 1.1.0
servers:
  - url: https://integration-staging.hotelios.uz
    description: Test server
  #- url: https://integration.hotelios.uz
  #  description: Prod server

tags:
  - name: Booking-Flow
    description: Search, book hotel rooms and cancel booking. Typical flow is **Search -> Quote -> Create -> Confirm**.

paths:
  /api/v1/booking-flow/search:
    post:
      tags: [ Booking-Flow ]
      summary: Search for possible booking variants.
      description: Note&#58; Result can be returned from the cache.
      operationId: v1_booking_flow_search
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BookingSearchRequest'
      responses:
        200:
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingSearchResponse'
              #examples:
              #  wrongLogin:
              #    errorCode: 1001

        
          
  /api/v1/booking-flow/quote:
    post:
      tags: [ Booking-Flow ]
      summary: Check the actual availability and prices for the booking option.
      description:  Result is always actual, not cached. It is mandatory to call this endpoint before trying to create a booking. We recommend to call it right before the booking attempt.
      operationId: v1_booking_flow_quote
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BookingQuoteRequest'
            example:
              login: "api-000x-001"
              password: "************"
              access_key: "abcxxx***"
              data:
                options:
                - option_ref_id: "130|1020|7585|..."
                - option_ref_id: "130|1021|7586|..."
      responses:
        200:
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingQuoteResponse'
              examples:
                Success:
                  value:
                    success: true
                    data:
                      quote_id: "931264bd-6d0c-4abb-9a4f-a6cfe5e8eb3e"
                      hotel:
                        hotel_id: 130
                        options:
                          - option_ref_id: "130|1020|7585|..."
                            room_type_id: 1020
                            rate_plan_id: 7585
                            occupancy:
                              adults: 1
                              children_ages:
                                - 10
                            cancellation_policy:
                              cancellation_type: "nrf"
                            included_meal_options:
                              - 0
                            extra_bed_added: false
                            currency: "uzs"
                            price: 100500
                            price_breakdown:
                              daily_rates:
                                - date: "2024-12-01"
                                  amount: 50000
                                - date: "2024-12-02"
                                  amount: 50000
                              fees:
                                - type: "city_tax"
                                  amount: 500
                              information:
                                - type: "included_in_price"
                                  name: "city_tax"
                            rooms_count: 7
                          - option_ref_id: "130|1021|7586|..."
                            room_type_id: 1021
                            rate_plan_id: 7586
                            occupancy:
                              adults: 1
                              children_ages:
                                - 10
                            cancellation_policy:
                              cancellation_type: "rf"
                              free_cancellation_before_days: 2
                              cancellation_penalty:
                                type: "percent_first_night"
                                amount: 100
                              no_show_penalty:
                                type: "percent_first_night"
                                amount: 100
                            extra_bed_added: false
                            currency: "uzs"
                            price: 100900
                            price_breakdown:
                              daily_rates:
                                - date: "2024-12-01"
                                  amount: 50200
                                - date: "2024-12-02"
                                  amount: 50200
                              fees:
                                - type: "city_tax"
                                  amount: 500
                            rooms_count: 5
                Hotel not available error:
                  value:
                    success: false
                    description: "Requested hotel with ID 100 is not available for user api-000x-001"
                    code: 4200
                Hotel not found error:
                  value:
                    success: false
                    description: "Requested hotel with ID 131 not found"
                    code: 1016

  /api/v1/booking-flow/booking/create:
    post:
      tags: [ Booking-Flow ]
      summary: Create a new Booking.
      description:  Successful response does not mean that room is really reserved. You need to call Confirm action afterwards. We recommend to keep period between Create and Confirm short enough. This period should be enough for person to enter his payment details and pay to your company.
      operationId: v1_booking_flow_booking_create  
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BookingCreateRequest'
            example:
              login: "api-000x-001"
              password: "************"
              access_key: "abcxxx***"
              data:
                quote_id: "931264bd-6d0c-4abb-9a4f-a6cfe5e8eb3e"
                external_id: "288399"
                booking_rooms:
                  - option_ref_id: "130|1020|7585|..."
                    guests:
                      - person_title: "MR"
                        first_name: "Bruce"
                        last_name: "Wayne"
                        nationality: "us"
                      - person_title: "MR"
                        first_name: "Dick"
                        last_name: "Grayson"
                        nationality: "us"
                        age: 10
                    price: 100500
                comment: "Please, put extra pillows."
                delta_price:
                  amount: 100
                  percent: 2
                  matches: "all"
      responses:
        200:
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingCreateResponse'
              examples:
                Success:
                  value:
                    success: true
                    data:
                      booking_id: "25501"
                      price: 100499.99
                Booking already exists error:
                  value:
                    success: false
                    description: "Booking already exists"
                    code: 4300
                Quote not found error:
                  value:
                    success: false
                    description: "Quote with ID '111111bd-6d0c-4abb-9a4f-a6cfe5e8eb3e' requested by 'api-000x-001' not found"
                    code: 4300
                Hotel not available error:
                  value:
                    success: false
                    description: "Requested hotel with ID 100 is not available for user api-000x-001"
                    code: 4300
                Hotel not found error:
                  value:
                    success: false
                    description: "Requested hotel with ID 131 not found"
                    code: 1016
                Price changed error:
                  value:
                    success: false
                    description: "Price is changed"
                    code: 4301
                No available rooms error:
                  value:
                    success: false
                    description: "Booking (QuoteID=931264bd-6d0c-4abb-9a4f-a6cfe5e8eb3e) for hotel (ID=130) failed because no rooms (RoomTypeID=1020, RatePlanID=7585) available"
                    code: 4302

  /api/v1/booking-flow/booking/confirm:
    post:
      tags: [ Booking-Flow ]
      summary: Confirm booking created by Create action.
      description:  Booking is sent to hotel after this action. If you try to confirm the booking 2nd time - error will be returned.
      operationId: v1_booking_flow_booking_confirm   
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BookingConfirmRequest'
      responses:
        200:
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingConfirmResponse'
              examples:
                Success:
                  value:
                    success: true
                Booking not found error:
                  value:
                    success: false
                    description: "Booking '25001' not found"
                    code: 1016

                
  /api/v1/booking-flow/booking/cancel:
    post:
      tags: [ Booking-Flow ]
      summary: Cancel existing booking.
      description:  Cancel existing booking.
      operationId: v1_booking_flow_booking_cancel   
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BookingCancelRequest'
      responses:
        200:
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingCancelResponse'
              examples:
                Success:
                  value:
                    success: true
                Booking not found error:
                  value:
                    success: false
                    description: "Booking '25001' not found"
                    code: 1016
                
  /api/v1/booking-flow/booking/read:
    post:
      tags: [ Booking-Flow ]
      summary: Get details of existing booking.
      description:  Get details of existing booking.
      operationId: v1_booking_flow_booking_read   
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/BookingReadRequest'
      responses:
        200:
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingReadResponse'
              examples:
                Success:
                  value:
                    success: true
                    data:
                      booking_id: "12345"
                      external_id: "100500"
                      status: "PENDING"
                      hotel_id: 130
                      check_in: "2025/11/25 14:00"
                      check_out: "2025/11/27 12:00"
                      is_resident: false
                      booking_rooms:
                        - room_type_id: 1020
                          rate_plan_id: 7585
                          cancellation_policy:
                            cancellation_type: "rf"
                            free_cancellation_before_days: 2
                            cancellation_penalty:
                              type: "percent_first_night"
                              amount: 100
                            no_show_penalty:
                              type: "percent_first_night"
                              amount: 100
                          included_meal_options:
                            - 0
                          extra_bed_added: false
                          guests:
                            - person_title: "MR"
                              first_name: "Bruce"
                              last_name: "Wayne"
                              nationality: "us"
                            - person_title: "CHILD"
                              first_name: "Dick"
                              last_name: "Grayson"
                              nationality: "us"
                              age: 10
                          price: 100500
                          price_breakdown:
                            daily_rates:
                              - date: "2024-12-01"
                                amount: 50000
                              - date: "2024-12-02"
                                amount: 50000
                            fees:
                              - type: "city_tax"
                                amount: 500
                      currency: "uzs"
                      price: 100500
                      comment: "Please, put extra pillows."
                      hotel_confirmation_number: "20250101-12345-1234567890"
                Booking not found error:
                  value:
                    success: false
                    description: "Booking '25001' not found"
                    code: 1016

components:

  responses:
    
    GenericError:
      description: Error Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'

  schemas:
  
    ErrorDescription:
      type: string
      example: Error description
      nullable: true
      description: Text description of error. Exists if success = false.
      
    ErrorCode:
      type: integer
      example: 2000
      nullable: true
      description: Error code. Exists if success = false.

    GenericError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'

    
    UserLogin:
      type: string
      nullable: false
      example: "api-000x-001"
      description: API user login received from Hotelios team.
    
    Occupancy:
      type: object
      description: Examples of occupancies&#58; '1 adult', '2 adults', '1 adult and 2 children (1 and 5 years old)'
      properties:
        adults:
          type: integer
          example: 1
          description: "Number of adults. Should not be less 1."
          nullable: false
        children_ages:
          type: array
          example: [1, 10]
          items:
            type: integer
            description: "List of child ages. Can contain integer values in scope 0 - 17."
            nullable: true
            
    CancellationPolicyPenalty:
      type: object
      properties:
        type: 
          type: string
          enum: ['percent_first_night', 'percent_booking']
          description: '**percent_first_night** - % from the first night stay price; **percent_booking** - % from the whole period stay price.'
        amount:
          type: number
          example: 100
            
    CancellationPolicy:
      type: object
      description: Cancellation Policy.<br><br>
        **cancellation_penalty** - Penalty paid in case of cancelling room booking later than allowed by cancellation policy.<br><br>
        **no_show_penalty** - Penalty paid if guest will not arrive to hotel in check-in date.
      properties:
        cancellation_type: 
          type: string
          enum: ['rf', 'nrf']
          description: '**rf** - refundable; **nrf** - non-refundable'
        free_cancellation_before_days:
          type: number
          example: 2
          description: Free cancellation is available for the indicated days prior to the check-in date<br><br>
            i.e. reservation could be cancelled before N days from check-in-date.<br><br>
            **If value is missing or value=0 then reservation is Non-Refundable**
        cancellation_penalty:
          $ref: '#/components/schemas/CancellationPolicyPenalty'
        no_show_penalty:
          $ref: '#/components/schemas/CancellationPolicyPenalty'
          
    MealOptions:
      type: array
      nullable: true
      description: A list of meal options. <br><br>
        **0** - breakfast<br><br>
        **1** - lunch<br><br>
        **2** - dinner
      items:
        type: integer
        enum: [0, 1, 2]
        minItems: 0

    MealPlan:
      type: string
      nullable: true
      description: Meal Plan code. A convenience alternative to MealOptions list.<br><br>
        **RO** - room only (no meal) <br><br>
        **BB** - bed and breakfast <br><br>
        **HB** - half board (2 meals per day) <br><br>
        **FB** - full board (3 meals per day)
      enum: [ 'RO', 'BB', 'HB', 'FB' ]

    OptionRefId:
      type: string
      description: Generated unique identifier of booking option. It can be obtained from the Search query. Please, use it 'as is' without modifying, without trying to generate it yourself. Format of this identifier can be changed without prior notice.
      nullable: false
      example: "130|1020|7856|..."
          
    QuoteId:
      type: string
      example: 931264bd-6d0c-4abb-9a4f-a6cfe5e8eb3e
      nullable: false
      description: Quote ID returned by Quote operation. A mandatory field for Booking Create operation.<br><br>
                Quote ID has a limited lifetime. We do not guarantee its existence for period longer than 1 hour.
                
    Guest:
      type: object
      properties:
        person_title: 
          type: string
          example: MR
          nullable: false
          enum: ['MR', 'MRS', 'CHILD']
        first_name:
          type: string
          example: John
          nullable: false
        last_name:
          type: string
          example: Smith
          nullable: false
        nationality:
          type: string
          example: uz
          nullable: false
        age:
          type: integer
          example: 1
          nullable: true
          minimum: 0
          maximum: 17
          description: Age should be specified for CHILD guests. Should be in scope 0..17. Child age may influence room prices. For adults age can be skipped.
          
    RoomPriceBreakdown:
      type: object
      description: Detailed information about the price. Contains&#58;<br><br>
          **daily_rates** - price for daily stay
          **fees** - different kinds of fees applied. "city_tax", "early_check_in", "late_check_out", "extra_bed" can be found here.
      properties:
        daily_rates:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              amount:
                type: number
        fees:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: city_tax
              amount:
                type: number
                example: 60000.00
        information:
          type: array
          nullable: true
          items:
            type: object
            properties:
              type:
                type: string
                enum: ['included_in_price', 'message']
                example: included_in_price
              name:
                type: string
                example: city_tax
          description: Optional array of additional information. Main purpose currently - to give a hint that city tax is included in price. To be extended in future.

    DeltaPrice:
      type: object
      description: Optional parameter. If not specified, we will compare the price we get in Booking Create request and the actual price. If actual price is lower or equal then reservation process will continue. Otherwise the reservation process will be stopped.<br><br>
        The Delta Price indicates the price variation permitted by the Buyer (amount or percentage).<br><br>
        **matches = ALL** means that both conditions (amount and percentage) should meet the DeltaPrice criteria.<br><br>
         **matches = ANY** means that at least one of conditions (amount or percentage) should meet the DeltaPrice criteria.
      properties:
        amount:
          type: number
          example: 2.00
          nullable: true
        percent:
          type: number
          example: 1.00
          nullable: true
        matches:
          type: string
          example: ALL
          enum: ['ALL', 'ANY']

    BookingId:
      type: string
      description: Hotelios Booking ID. 5-60 characters.
      nullable: false
      example: 12345
      
    BookingComment:
      type: string
      example: "Please, put extra pillows."
      description: Reservation comment. Max 1000 characters.
      
    BookingSearchRequest:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/UserLogin'
        password:
          type: string
          nullable: false
        access_key:
          type: string
          nullable: false
        data:
          type: object
          nullable: false
          properties:
            city_id:
              type: integer
              example: 67
              description: "City Id. Either city_id or hotel_ids must be defined."
              nullable: true
            hotel_ids:
              type: array
              items:
                type: integer
              example: [130]
              description: "Hotel id list. Either city_id or hotel_ids must be defined."
              nullable: true
            check_in:
              type: string
              example: '2025/11/25 14:00'
              description: "Check-in date."
              nullable: false
            check_out:
              type: string
              example: '2025/11/27 12:00'  
              description: "Check-out date. Should be later than check-in date."
              nullable: false
            is_resident:
              type: boolean
              example: false
              description: "In most cases is false. Set true if you wish to have prices for Uzbekistan residents. If at least one of guests is not Uzbekistan resident - prices for non-residents should be queried."
              nullable: true
            occupancies:
              description: "List of occupancies."
              type: array
              items:
                $ref: '#/components/schemas/Occupancy'
                
            currency:
              type: string
              example: "uzs"
              description: "Currency code. We recommend to search for prices using hotel currency. Then no unnecessary currency conversions are applied."
              nullable: false
            price_min:
              type: number
              example: 5.00
              description: "An optional filter. Restricts the result list by MIN Price"
              nullable: true
            price_max:
              type: number
              example: 1000000000.00
              description: "An optional filter. Restricts the result list by MAX Price"
              nullable: true
            stars:
              description: "An optional filter. Restricts the result by hotel star categories. Please, call GetStarList action for a list of available ids."
              type: array
              items:
                type: integer
              example: [3, 4, 5]
              nullable: true
            facilities:
              description: "An optional filter. Restricts the result by hotel facilities. Please, call GetFacilityList action for a list of available ids."
              type: array
              items:
                type: integer
              nullable: true
            equipments:
              description: "An optional filter. Restricts the result by room equipments. Please, call GetEquipmentList action for a list of available ids."
              type: array
              items:
                type: integer
              nullable: true
            cancellation_type:
              description: "An optional filter. Restricts the result by cancellation type. **rf** - refundable; **nrf** - non-refundable; **all** - do not filter by cancellation type (alternatively you can simply do not include 'cancellation_type' in request)."
              type: string
              enum: [ 'rf', 'nrf', 'all' ]
              nullable: true
            meal_plans:
              description: "An optional filter. Restricts the result by meal plan."
              type: array
              items:
                $ref: '#/components/schemas/MealPlan'
              nullable: true
            hotel_types:
              description: "An optional filter. Restricts the result by hotel type. List of available hotel types can be retrieved by GetHotelTypeList method. In most cases you do not need to specify this filter."
              type: array
              items:
                type: integer
              nullable: true
              example: [1, 2, 3, 4, 5, 10, 11]
            #sort_by:
            #  type: integer
            #  example: 1
            #  enum: [0, 1, 2, 3]
            #  description: Allows to sort the search result list.
            #    **0** - Recommended. 
            #    **1** - Price.
            #    **2** - Hotel name.
            #    **3** - Stars.
            #  nullable: true
            #sort_order:
            #  type: string
            #  enum:
            #    - 'asc'
            #    - 'desc'
            #  description: Allows to order specify the sort order (asc or desc).
            #  nullable: true
              
    BookingSearchResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        data:
          type: object
          properties:
            hotels:
              type: array
              description: A list of hotel objects containing booking options (rooms)
              items:
                type: object
                properties:
                  hotel_id:
                    type: integer
                    nullable: false
                  options:
                    type: array
                    description: A list of hotel booking options (rooms)
                    nullable: false
                    items:
                      type: object
                      properties:
                        option_ref_id:
                          $ref: '#/components/schemas/OptionRefId'
                        room_type_id:
                          type: integer
                          description: Unique room type (category) identifier. Each hotel has own room type list. Room_type_id is unique in scope of hotel and globally.
                          nullable: false
                        rate_plan_id:
                          type: integer
                          nullable: false
                        occupancy:
                          $ref: '#/components/schemas/Occupancy'
                        cancellation_policy:
                          $ref: '#/components/schemas/CancellationPolicy'
                        included_meal_options:
                          $ref: '#/components/schemas/MealOptions'
                        extra_bed_added:
                          type: boolean
                          example: false
                          description: Will be 'true' if one of guests stays on extra bed.
                        currency:
                          type: string
                          example: "UZS"
                          description: "Currency code."
                          nullable: false
                        price:
                          type: number
                          example: 100.50
                          description: Total Price for the room for the booking period for current occupancy. Detailed price information can be retrieved by calling Quote method.
                        rooms_count:
                          type: number
                          example: 5
                          description: Number of rooms available for booking.
                      
    BookingQuoteRequest:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/UserLogin'
        password:
          type: string
          nullable: false
          example: "************"
        access_key:
          type: string
          nullable: false
          example: "abcxxx***"
        data:
          type: object
          nullable: false
          properties:
            options:
              type: array
              description: List of option ids returned by Search query
              items:
                type: object
                properties:
                  option_ref_id:
                    $ref: '#/components/schemas/OptionRefId'
                    
                    
    BookingQuoteResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        data:
          type: object
          properties:
            quote_id:
              $ref: '#/components/schemas/QuoteId'
            hotel:
              type: object
              description: Detailed and actual information about booking options.
              properties:
                hotel_id:
                  type: number
                  description: Hotel ID
                  example: 130
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      option_ref_id:
                        $ref: '#/components/schemas/OptionRefId'
                      room_type_id:
                        type: integer
                        description: Unique room type (category) identifier. Each hotel has own room type list. Room_type_id is unique in scope of hotel and globally.
                        nullable: false
                        example: 320
                      rate_plan_id:
                        type: integer
                        nullable: false
                        example: 690
                      occupancy:
                        $ref: '#/components/schemas/Occupancy'
                      cancellation_policy:
                        $ref: '#/components/schemas/CancellationPolicy'
                      included_meal_options:
                        $ref: '#/components/schemas/MealOptions'
                      extra_bed_added:
                        type: boolean
                        description: Will be 'true' if one of guests stays on extra bed.
                        example: false
                      currency:
                        type: string
                        description: "Currency code."
                        nullable: false
                        example: "uzs"
                      price:
                        type: number
                        description: Total Price for the room for the booking period for current occupancy. Detailed price information can be retrieved by calling Quote method.
                        example: 100499.99
                      price_breakdown:
                        $ref: '#/components/schemas/RoomPriceBreakdown'
                      rooms_count:
                        type: number
                        description: Number of rooms available for booking.
                        example: 5
                        
    BookingCreateRequest:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/UserLogin'
        password:
          type: string
          nullable: false
        access_key:
          type: string
          nullable: false
        data:
          type: object
          nullable: false
          properties:
            quote_id:
              $ref: '#/components/schemas/QuoteId'
            external_id:
              type: string
              description: please put here your internal id of reservation. **ID MUST BE UNIQUE**
              nullable: false
            booking_rooms:
              type: array
              description: List of rooms to be booked
              items:
                type: object
                properties:
                  option_ref_id:
                    $ref: '#/components/schemas/OptionRefId'
                  guests:
                    type: array
                    description: List of guests. At least one adult must be in a room.
                    items:
                      $ref: '#/components/schemas/Guest'
                  price:
                    type: number
                    example: 100000.51
                    description: Total Price for the room for the booking period for current occupancy.
                    nullable: false
            comment: 
              $ref: '#/components/schemas/BookingComment'
            deltaPrice:
              $ref: '#/components/schemas/DeltaPrice'
              
                    
                    
    BookingCreateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        data:
          type: object
          properties:
            booking_id:
              $ref: '#/components/schemas/BookingId'
            price:
              type: number
              description: Total Price for the complete created booking. May be different from the price you sent to Create action. Difference may happen if room price decreased right before booking. Or in case price increased and new price fits deltaPrice specified by you in Create request.
              nullable: true
              example: 100000.51
              
    BookingConfirmRequest:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/UserLogin'
        password:
          type: string
          nullable: false
        access_key:
          type: string
          nullable: false
        data:
          type: object
          nullable: false
          properties:
            booking_id:
              $ref: '#/components/schemas/BookingId'
              
    BookingConfirmResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
          
    BookingCancelRequest:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/UserLogin'
        password:
          type: string
          nullable: false
        access_key:
          type: string
          nullable: false
        data:
          type: object
          nullable: false
          properties:
            booking_id:
              $ref: '#/components/schemas/BookingId'
              
    BookingCancelResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
            
    BookingReadRequest:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/UserLogin'
        password:
          type: string
          nullable: false
        access_key:
          type: string
          nullable: false
        data:
          type: object
          nullable: false
          properties:
            booking_id:
              $ref: '#/components/schemas/BookingId'
              
    BookingReadResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        description:
          $ref: '#/components/schemas/ErrorDescription'
        errorCode:
          $ref: '#/components/schemas/ErrorCode'
        data:
          type: object
          properties:
            booking_id:
              $ref: '#/components/schemas/BookingId'
            status:
              type: string
              nullable: false
              enum: ['PENDING', 'WAIT_LIST', 'CONFIRMED', 'CANCELLED']
              description: '**PENDING** - not confirmed by hotel yet; **WAIT_LIST** - hotel cannot confirm booking and puts it to wait list; **CONFIRMED** - confirmed by hotel; **CANCELLED** - cancelled'
              example: PENDING
            hotel_id:
              type: integer
              nullable: false
              example: 130
            check_in:
              type: string
              example: '2025/11/25 14:00'
              description: "Check-in date."
              nullable: false
            check_out:
              type: string
              example: '2025/11/27 12:00'  
              description: "Check-out date."
              nullable: false
            is_resident:
              type: boolean
              example: false
              nullable: false
            booking_rooms:
              type: array
              items:
                type: object
                properties:
                  room_type_id:
                    type: integer
                    description: Unique room type (category) identifier. Each hotel has own room type list. Room_type_id is unique in scope of hotel and globally.
                    nullable: false
                  rate_plan_id:
                    type: integer
                    nullable: false

                  cancellation_policy:
                    $ref: '#/components/schemas/CancellationPolicy'
                  included_meal_options:
                    $ref: '#/components/schemas/MealOptions'
                  guests:
                    type: array
                    items:
                      $ref: '#/components/schemas/Guest'
                  extra_bed_added:
                    type: boolean
                    example: false
                    description: Will be 'true' if one of guests stays on extra bed.
                  price:
                    type: number
                    example: 100000.51
                  price_breakdown:
                    $ref: '#/components/schemas/RoomPriceBreakdown'
            currency:
              type: string
              example: "UZS"
              description: "Currency code."
              nullable: false
            price:
              type: number
              example: 100000.51
              nullable: false
            comment:
              $ref: '#/components/schemas/BookingComment'
            hotel_confirmation_number:
              type: string
              example: "20250101-12345-1234567890"
              description: "Hotel Confirmation Number. Format may depend on Hotel."
              nullable: true

                  
              

